

# Auto run Tmux when the terminal starts
# -A will attach to existing session if it exists
#[shell]
#program = "/opt/homebrew/bin/tmux"
#args = ["new-session", "-A", "-s", "🏡 Home"]
# Obs! When all sessions are cloeed, tmux loads without the theme, I had to remove the lines above and run:
# tmux new -s "Home"



[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[colors.primary]
foreground = "#1bd81e"

[scrolling]
history = 10000
multiplier = 3

[window]
# decorations = "buttonless"
# Options are: "none", "buttonless", "full"
decorations = "full"

dynamic_padding = false
opacity = 0.95
#startup_mode = "SimpleFullscreen"
#Options are "SimpleFullscreen", "Fullscreen", "Maximized", "Windowed"
startup_mode = "Windowed"
padding = { x = 15, y = 15 }

dynamic_title = false
title = "eystein.bye@disruptive-technologies.com 💻"

#position = { x = 300, y = 220 }
#dimensions = { columns = 120, lines = 34 }

# This will remove the option key, and will make it hard to
# write signs like: \{}~ etc
# option_as_alt = "OnlyLeft"

[cursor]
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
style = "Beam"


# Changes wanted!
# - Remove selection when using arrow keys
# - Send BS delete to remove selected text
# - keep cursor in the same position when scrolling




# -----------------------------------------------------------------------------
# Keybindings - Tmux - Binds Ctrl+B, key
# -----------------------------------------------------------------------------
#
#
# TMUX mappings of CMD
# Mapping CMD combinations and sending them as Ctrl+B as TMUX uses Ctrl+B as the prefix
# D T W Arrow Tab
# This will make Alacritty work like iTerm2 with Tmux

# Fullscreen - Cmd+Enter
[[keyboard.bindings]]
action = "ToggleMaximized"
key = "Enter"
mods = "Command"

# Start Sesh - Cmd+J
# This can also be started in a new shell with the command: t
[[keyboard.bindings]]
chars = "\u0002T" # Sends Ctrl+B, T
key = "J"
mods = "Command"

# Start SessionX - Cmd+O
[[keyboard.bindings]]
chars = "\u0002o" # Sends Ctrl+B, o
key = "O"
mods = "Command"

# Start Eysteins Port-forward in tmux session
[[keyboard.bindings]]
chars = "\u0002i"
key = "P"
mods = "Command"

# Split pane horizontally
[[keyboard.bindings]]
chars = "\u0002\"" # Sends Ctrl+B, "
key = "D"
mods = "Command"

# Split pane vertically
[[keyboard.bindings]]
chars = "\u0002%" # Sends Ctrl+B, %
key = "D"
mods = "Command|Shift"

# Zoom pane - Toggle - Shift+Cmd+Enter
[[keyboard.bindings]]
chars = "\u0002z" # Sends Ctrl+B, z
key = "Enter"
mods = "Shift|Command"

# Create new Tmux window - Cmd+T
[[keyboard.bindings]]
chars = "\u0002c" # Sends Ctrl+B, c
key = "T"
mods = "Command"

# Switch to next Tmux window - Ctrl+Tab
[[keyboard.bindings]]
chars = "\u0002n" # Sends Ctrl+B, n
key = "Tab"
mods = "Control"

# Close pane or Window - Cmd+W
[[keyboard.bindings]]
chars = "\u0002x" # Sends Ctrl+B, x
key = "W"
mods = "Command"

# Focus upper pane - Ctrl+Cmd+Up
[[keyboard.bindings]]
chars = "\u0002j" # Sends Ctrl+B, j
key = "Up"
mods = "Command|Control"

# Focus lower pane - Ctrl+Cmd+Down
[[keyboard.bindings]]
chars = "\u0002k" # Sends Ctrl+B, k
key = "Down"
mods = "Command|Control"

# Focus right pane - Ctrl+Cmd+Right
[[keyboard.bindings]]
chars = "\u0002L" # Sends Ctrl+B, l
key = "Right"
mods = "Command|Control"

# Focus left pane - Ctrl+Cmd+Left
[[keyboard.bindings]]
chars = "\u0002h" # Sends Ctrl+B, h
key = "Left"
mods = "Command|Control"

# Same as above, but mapped to Cmd+Option+Arrow
# Focus upper pane - Ctrl+Option+Up
[[keyboard.bindings]]
chars = "\u0002j" # Sends Ctrl+B, j
key = "Up"
mods = "Command|Option"

# Focus lower pane - Ctrl+Option+Down
[[keyboard.bindings]]
chars = "\u0002k" # Sends Ctrl+B, k
key = "Down"
mods = "Command|Option"

# Focus right pane - Ctrl+Option+Right
[[keyboard.bindings]]
chars = "\u0002l" # Sends Ctrl+B, l
key = "Right"
mods = "Command|Option"

# Focus left pane - Ctrl+Option+Left
[[keyboard.bindings]]
chars = "\u0002h" # Sends Ctrl+B, h
key = "Left"
mods = "Command|Option"

# Show the Tmux clipboard buffer - Cmd+Shift+V
[[keyboard.bindings]]
chars = "\u0002=" # Sends Ctrl+B, =
key = "V"
mods = "Command|Option"



# -----------------------------------------------------------------------------
# Keybindings - Macos CMD - keys
# -----------------------------------------------------------------------------




# SELECT ALL
# Capture Cmd+A and send it as Ctrl+D, A so Vim can map it to select all
[[keyboard.bindings]]
chars = "\u0007A" # Sends Ctrl+D, A
key = "A"
mods = "Command"

# COPY
# Capture Cmd+C and send it as Ctrl+D, C so Vim can map it to copy
[[keyboard.bindings]]
chars = "\u0007C" # Sends Ctrl+D, C
key = "C"
mods = "Command"

# FIND
# Map Cmd+F to Ctrl+D, F so Vim can map it to search
[[keyboard.bindings]]
chars = "\u0007F" # Sends Ctrl+D, F
key = "F"
mods = "Command"

# FIND IN FILES
# Map Cmd+Shift+F to Ctrl+D, O so Vim can map it Find in files
[[keyboard.bindings]]
chars = "\u0007O" # Sends Ctrl+D, O
key = "F"
mods = "Command|Shift"

# GIT
# Map Cmd+G to Ctrl+D, G so Vim can map it
[[keyboard.bindings]]
chars = "\u0007G" # Sends Ctrl+D, G
key = "G"
mods = "Command"

# OPEN FILE
# Map Cmd+P to Ctrl+D, P so Vim can map it to open the file finder
[[keyboard.bindings]]
chars = "\u0007P" # Sends Ctrl+D, P
key = "P"
mods = "Command"

# COMMAND PALETTE
# Map Cmd+Shift+P to Ctrl+D, K so Vim can map it
[[keyboard.bindings]]
chars = "\u0007K" # Sends Ctrl+D, K
key = "P"
mods = "Command|Shift"

# SAVE
# Capture Cmd+S an send it as Ctrl+D, S so Vim can map it to save
[[keyboard.bindings]]
chars = "\u0007S" # Sends Ctrl+D, S
key = "S"
mods = "Command"

# UNDO
# Capture Cmd+z and send it as Ctrl+D, Z so Vim can map it to undo
# Ctrl+y
[[keyboard.bindings]]
chars = "\u0007Z" # Sends Ctrl+D, Z
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007X" # Sends Ctrl+D, X
key = "X"
mods = "Command"

[general]
# https://alacritty.org/config-alacritty.html
# Examples:
# https://github.com/alacritty/alacritty/blob/v0.8.0/alacritty.yml#L370
#
# https://www.joshmedeski.com/posts/a-pretty-terminal-in-5-minutes/
# https://www.joshmedeski.com/posts/macos-keyboard-shortcuts-for-tmux/

live_config_reload = true


# -----------------------------------------------------------------------------
#
# 

# Bind Cmd Arrow up to Ctrl+Up
# [[keyboard.bindings]]
# chars = """:TSTextobjectGotoPreviousStart @function.outer
# """
# key = "Up"
# mods = "Command"
#
# # Bind Cmd Arrow down to Ctrl+Down
# [[keyboard.bindings]]
# chars = """:TSTextobjectGotoNextStart @function.outer
# """
# key = "Down"
# mods = "Command"
#


# Binf Cmd + arrow right to end
# [[keyboard.bindings]]
# chars = """
# key = "Right"
# mods = "Command"
#
#
#

